(() => {
  const apiBase=(window.APP_CONFIG?.API_BASE_URL||"").replace(/\/$/,"");
  const byId=id=>document.getElementById(id);
  let activeTab="pending";let games=[];let users=[];
  const readSession=()=>{for(const s of [localStorage,sessionStorage]){try{const raw=s.getItem("lacvietgamesStoreSession");if(raw)return JSON.parse(raw)}catch{}}return null};
  const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  async function api(path,options={}){const session=readSession();if(!session?.token)throw Object.assign(new Error("Bạn cần đăng nhập."),{code:"AUTH_REQUIRED"});const response=await fetch(`${apiBase}${path}`,{method:options.method||"GET",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.token}`},body:options.body?JSON.stringify(options.body):undefined});const payload=await response.json().catch(()=>null);if(!response.ok||payload?.success===false)throw Object.assign(new Error(payload?.message||"Không thể xử lý yêu cầu."),{code:payload?.code});return payload}
  function status(message,error=false){const el=byId("adminStatus");el.textContent=message;el.classList.toggle("error",error)}

  async function boot(){
    try{const me=await api("/api/store/me");if(String(me.data.role).toLowerCase()!=="admin")throw Object.assign(new Error("Tài khoản hiện tại không có quyền Admin."),{code:"FORBIDDEN"});byId("adminDenied").hidden=true;byId("adminContent").hidden=false;await loadGames(true)}
    catch(error){byId("adminContent").hidden=true;byId("adminDenied").hidden=false;byId("adminDeniedText").textContent=error.message}
  }

  async function loadGames(pendingOnly=activeTab==="pending"){
    byId("adminGameList").innerHTML='<div class="portal-empty">Đang tải...</div>';
    try{const result=await api(`/api/store/admin/games${pendingOnly?"?status=Pending":""}`);games=result.data||[];renderGames()}catch(error){byId("adminGameList").innerHTML=`<div class="portal-empty" style="color:#ff9dab">${esc(error.message)}</div>`}
  }

  function renderGames(){
    byId("adminGameList").innerHTML=games.length?games.map(g=>`<article class="admin-item"><div class="admin-top"><div><h3>${esc(g.icon||"🎮")} ${esc(g.name)}</h3><p>${esc(g.publisherName)} · ${esc(g.type)} · ${Number(g.priceCoins||0).toLocaleString("vi-VN")} LC</p></div><span class="status-chip ${String(g.status).toLowerCase()}">${esc(g.status)}</span></div><div class="tag-stack">${(g.tags||[]).map(t=>`<span>${esc(t)}</span>`).join("")}</div><p style="margin-top:10px">${esc(g.shortDescription||"")}</p>${g.rejectionReason?`<p style="margin-top:8px;color:#ff9dab">${esc(g.rejectionReason)}</p>`:""}<div class="admin-actions"><button class="mini-btn primary" data-approve="${g.id}">Duyệt</button><button class="mini-btn danger" data-reject="${g.id}">Từ chối</button><button class="mini-btn" data-edit-game="${g.id}">Sửa thông tin</button></div></article>`).join(""):'<div class="portal-empty">Không có game phù hợp.</div>';
  }

  async function approve(id){try{status("Đang duyệt game...");const result=await api(`/api/store/admin/games/${id}/approve`,{method:"POST"});status(result.message);await loadGames()}catch(error){status(error.message,true)}}
  async function reject(id){const reason=prompt("Lý do từ chối game:","Cần chỉnh sửa thông tin trước khi xuất bản.");if(reason===null)return;try{status("Đang cập nhật...");const result=await api(`/api/store/admin/games/${id}/reject`,{method:"POST",body:{reason}});status(result.message);await loadGames()}catch(error){status(error.message,true)}}

  function openEdit(id){const g=games.find(x=>Number(x.id)===Number(id));if(!g)return;byId("editGameId").value=g.id;byId("editName").value=g.name||"";byId("editSlug").value=g.slug||"";byId("editType").value=g.type||"web";byId("editPrice").value=g.priceCoins||0;byId("editStatus").value=g.status||"Pending";byId("editPublisher").value=g.publisherName||"";byId("editShort").value=g.shortDescription||"";byId("editDescription").value=g.description||"";byId("editTags").value=(g.tags||[]).join(", ");byId("editCover").value=g.coverUrl||"";byId("editPlay").value=g.playUrl||"";byId("editDownload").value=g.downloadUrl||"";byId("editOs").value=g.requirements?.os||"";byId("editCpu").value=g.requirements?.cpu||"";byId("editRam").value=g.requirements?.ram||"";byId("editGpu").value=g.requirements?.gpu||"";byId("editStorage").value=g.requirements?.storage||"";byId("editRejectReason").value=g.rejectionReason||"";byId("adminEditModal").hidden=false;document.body.style.overflow="hidden"}
  function closeEdit(){byId("adminEditModal").hidden=true;document.body.style.overflow=""}

  async function saveEdit(event){event.preventDefault();const id=Number(byId("editGameId").value);const payload={name:byId("editName").value.trim(),slug:byId("editSlug").value.trim(),publisherName:byId("editPublisher").value.trim(),type:byId("editType").value,priceCoins:Number(byId("editPrice").value||0),shortDescription:byId("editShort").value.trim(),description:byId("editDescription").value.trim(),tags:byId("editTags").value.split(",").map(v=>v.trim()).filter(Boolean),coverUrl:byId("editCover").value.trim(),playUrl:byId("editPlay").value.trim(),downloadUrl:byId("editDownload").value.trim(),icon:games.find(g=>Number(g.id)===id)?.icon||"🎮",badge:games.find(g=>Number(g.id)===id)?.badge||"",theme:games.find(g=>Number(g.id)===id)?.theme||"default",releaseDate:games.find(g=>Number(g.id)===id)?.releaseDate||null,recommendedOs:byId("editOs").value.trim(),recommendedCpu:byId("editCpu").value.trim(),recommendedRam:byId("editRam").value.trim(),recommendedGpu:byId("editGpu").value.trim(),recommendedStorage:byId("editStorage").value.trim(),status:byId("editStatus").value,rejectionReason:byId("editRejectReason").value.trim()};try{const result=await api(`/api/store/admin/games/${id}`,{method:"PUT",body:payload});status(result.message);closeEdit();await loadGames(false)}catch(error){status(error.message,true)}}

  async function loadUsers(){byId("adminUserList").innerHTML='<div class="portal-empty">Đang tải...</div>';try{const result=await api("/api/store/admin/users");users=result.data||[];renderUsers()}catch(error){byId("adminUserList").innerHTML=`<div class="portal-empty" style="color:#ff9dab">${esc(error.message)}</div>`}}
  function renderUsers(){const q=byId("userSearch").value.trim().toLowerCase();const filtered=users.filter(u=>!q||`${u.name} ${u.email}`.toLowerCase().includes(q));byId("adminUserList").innerHTML=filtered.length?filtered.map(u=>`<article class="admin-item user-row" data-user-row="${u.id}"><input data-user-name value="${esc(u.name)}"><div><b>${esc(u.email)}</b><small style="display:block;color:#7f8da7">${u.isEmailVerified?"Đã xác minh":"Chưa xác minh"}</small></div><select data-user-role><option ${u.role==="User"?"selected":""}>User</option><option ${u.role==="Admin"?"selected":""}>Admin</option></select><b>🪙 ${Number(u.coinBalance||0).toLocaleString("vi-VN")}</b><div class="admin-actions" style="margin:0"><button class="mini-btn primary" data-save-user="${u.id}">Lưu</button><button class="mini-btn" data-adjust-coin="${u.id}">± Coin</button></div></article>`).join(""):'<div class="portal-empty">Không tìm thấy người dùng.</div>'}
  async function saveUser(id){const row=document.querySelector(`[data-user-row="${id}"]`);try{const result=await api(`/api/store/admin/users/${id}`,{method:"PUT",body:{name:row.querySelector("[data-user-name]").value.trim(),role:row.querySelector("[data-user-role]").value}});status(result.message);await loadUsers()}catch(error){status(error.message,true)}}
  async function adjustCoin(id){const amountText=prompt("Nhập số coin cần cộng hoặc trừ. Ví dụ 500 hoặc -200:","500");if(amountText===null)return;const amount=Number(amountText);if(!Number.isInteger(amount)||amount===0)return alert("Số coin không hợp lệ.");const reason=prompt("Lý do điều chỉnh:","Hỗ trợ người dùng")||"Điều chỉnh bởi Admin";try{const result=await api(`/api/store/admin/users/${id}/coins`,{method:"POST",body:{amount,reason}});status(result.message);await loadUsers()}catch(error){status(error.message,true)}}

  document.addEventListener("click",event=>{const tab=event.target.closest("[data-admin-tab]");if(tab){document.querySelectorAll("[data-admin-tab]").forEach(b=>b.classList.remove("active"));tab.classList.add("active");activeTab=tab.dataset.adminTab;const usersTab=activeTab==="users";byId("adminGamesPanel").hidden=usersTab;byId("adminUsersPanel").hidden=!usersTab;if(usersTab)loadUsers();else loadGames(activeTab==="pending");return}const approveId=event.target.closest("[data-approve]")?.dataset.approve;if(approveId)return approve(approveId);const rejectId=event.target.closest("[data-reject]")?.dataset.reject;if(rejectId)return reject(rejectId);const editId=event.target.closest("[data-edit-game]")?.dataset.editGame;if(editId)return openEdit(editId);const saveId=event.target.closest("[data-save-user]")?.dataset.saveUser;if(saveId)return saveUser(saveId);const coinId=event.target.closest("[data-adjust-coin]")?.dataset.adjustCoin;if(coinId)return adjustCoin(coinId)});
  byId("refreshAdmin").addEventListener("click",()=>loadGames(activeTab==="pending"));byId("userSearch").addEventListener("input",renderUsers);byId("closeAdminEdit").addEventListener("click",closeEdit);byId("adminGameForm").addEventListener("submit",saveEdit);byId("adminEditModal").addEventListener("click",e=>{if(e.target===byId("adminEditModal"))closeEdit()});
  setTimeout(boot,0);
})();
