(() => {
  const apiBase=(window.APP_CONFIG?.API_BASE_URL||"").replace(/\/$/,"");
  const byId=id=>document.getElementById(id);
  const emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const existing=localStorage.getItem("lacvietgamesSession")||sessionStorage.getItem("lacvietgamesSession");
  if(existing&&new URLSearchParams(location.search).get("force")!=="1") location.replace("./index.html");

  function status(message,type="error"){const el=byId("authStatus");el.textContent=message;el.className=`auth-status show ${type}`}
  function clearStatus(){const el=byId("authStatus");el.textContent="";el.className="auth-status"}
  function error(input,message){input.classList.add("invalid");const small=input.closest("label")?.querySelector("small");if(small)small.textContent=message}
  function clearErrors(form){form.querySelectorAll("input").forEach(i=>i.classList.remove("invalid"));form.querySelectorAll("label small").forEach(s=>s.textContent="");clearStatus()}
  async function api(path,body){let response;try{response=await fetch(`${apiBase}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})}catch{throw new Error("Không thể kết nối máy chủ LacVietGames.")}const payload=await response.json().catch(()=>null);if(!response.ok||payload?.success===false)throw Object.assign(new Error(payload?.message||"Không thể xử lý yêu cầu."),{payload});return payload}
  function loading(button,value,label){button.disabled=value;if(value){button.dataset.label=button.textContent;button.textContent=label}else button.textContent=button.dataset.label||label}
  function showMain(tab="login"){byId("mainAuthPanel").hidden=false;byId("forgotForm").hidden=true;byId("resetForm").hidden=true;document.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));byId("loginForm").classList.toggle("active",tab==="login");byId("registerForm").classList.toggle("active",tab==="register");clearStatus()}

  document.querySelectorAll("[data-tab]").forEach(btn=>btn.addEventListener("click",()=>showMain(btn.dataset.tab)));
  document.querySelectorAll("[data-toggle]").forEach(btn=>btn.addEventListener("click",()=>{const input=byId(btn.dataset.toggle),show=input.type==="password";input.type=show?"text":"password";btn.textContent=show?"Ẩn":"Hiện"}));
  document.querySelectorAll("input").forEach(input=>input.addEventListener("input",()=>{input.classList.remove("invalid");const small=input.closest("label")?.querySelector("small");if(small)small.textContent=""}));
  document.querySelectorAll(".auth-back").forEach(btn=>btn.addEventListener("click",()=>showMain("login")));
  byId("forgotButton").addEventListener("click",()=>{byId("mainAuthPanel").hidden=true;byId("forgotForm").hidden=false;byId("forgotEmail").value=byId("loginEmail").value;clearStatus()});

  byId("loginForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,email=byId("loginEmail"),password=byId("loginPassword");clearErrors(form);let valid=true;if(!emailPattern.test(email.value.trim())){error(email,"Email không đúng định dạng.");valid=false}if(!password.value){error(password,"Vui lòng nhập mật khẩu.");valid=false}if(!valid)return;const btn=form.querySelector("button[type=submit]");loading(btn,true,"Đang đăng nhập...");try{const result=await api("/api/Accounts/login",{email:email.value.trim().toLowerCase(),password:password.value});const account=result.data;const session={id:account.accId,name:account.accName,email:account.accEmail,verified:account.isEmailVerified,loginAt:new Date().toISOString()};localStorage.removeItem("lacvietgamesSession");sessionStorage.removeItem("lacvietgamesSession");(byId("rememberMe").checked?localStorage:sessionStorage).setItem("lacvietgamesSession",JSON.stringify(session));location.assign("./index.html")}catch(err){status(err.message)}finally{loading(btn,false,"Đăng nhập")}});

  byId("registerForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,name=byId("registerName"),email=byId("registerEmail"),password=byId("registerPassword"),confirm=byId("registerConfirm");clearErrors(form);byId("termsError").textContent="";let valid=true;if(name.value.trim().length<2){error(name,"Tên phải có ít nhất 2 ký tự.");valid=false}if(!emailPattern.test(email.value.trim())){error(email,"Email không đúng định dạng.");valid=false}if(password.value.length<8){error(password,"Mật khẩu phải có ít nhất 8 ký tự.");valid=false}if(confirm.value!==password.value){error(confirm,"Mật khẩu xác nhận không khớp.");valid=false}if(!byId("acceptTerms").checked){byId("termsError").textContent="Bạn cần đồng ý với điều khoản sử dụng.";valid=false}if(!valid)return;const btn=form.querySelector("button[type=submit]");loading(btn,true,"Đang gửi mã...");try{const result=await api("/api/Accounts/register",{name:name.value.trim(),email:email.value.trim().toLowerCase(),password:password.value});if(!result.data?.registrationToken)throw new Error("Máy chủ chưa trả về phiên xác thực.");sessionStorage.setItem("lacvietgamesPendingRegistration",JSON.stringify({name:name.value.trim(),email:result.data.email||email.value.trim().toLowerCase(),registrationToken:result.data.registrationToken,expiresInMinutes:result.data.expiresInMinutes||15,startedAt:Date.now()}));location.assign("./verify.html")}catch(err){status(err.message)}finally{loading(btn,false,"Gửi mã xác nhận")}});

  byId("forgotForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,email=byId("forgotEmail");clearErrors(form);if(!emailPattern.test(email.value.trim())){error(email,"Email không đúng định dạng.");return}const btn=form.querySelector("button[type=submit]");loading(btn,true,"Đang gửi...");try{const normalized=email.value.trim().toLowerCase(),result=await api("/api/Accounts/forgot-password",{email:normalized});byId("forgotForm").hidden=true;byId("resetForm").hidden=false;byId("resetEmail").value=normalized;status(result.message,"success")}catch(err){status(err.message)}finally{loading(btn,false,"Gửi mã khôi phục")}});

  byId("resetForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,email=byId("resetEmail"),code=byId("resetCode"),password=byId("resetPassword"),confirm=byId("resetConfirm");clearErrors(form);let valid=true;if(!emailPattern.test(email.value.trim())){error(email,"Email không đúng định dạng.");valid=false}if(!/^\d{6}$/.test(code.value.trim())){error(code,"Mã phải gồm 6 chữ số.");valid=false}if(password.value.length<8){error(password,"Mật khẩu phải có ít nhất 8 ký tự.");valid=false}if(confirm.value!==password.value){error(confirm,"Mật khẩu xác nhận không khớp.");valid=false}if(!valid)return;const btn=form.querySelector("button[type=submit]");loading(btn,true,"Đang cập nhật...");try{const result=await api("/api/Accounts/reset-password",{email:email.value.trim().toLowerCase(),code:code.value.trim(),newPassword:password.value});showMain("login");byId("loginEmail").value=email.value.trim().toLowerCase();status(result.message,"success")}catch(err){status(err.message)}finally{loading(btn,false,"Đặt lại mật khẩu")}});

  showMain(new URLSearchParams(location.search).get("tab")==="register"?"register":"login");
})();
