window.LVG_GAMES = [
  {
    id: "oops-brake",
    title: "Oops! Brake",
    studio: "Lạc Việt Forge",
    type: "download",
    platform: ["Windows", "macOS"],
    category: ["Đua xe", "Casual"],
    price: 1290,
    oldPrice: 1790,
    rating: 4.8,
    reviews: 1248,
    badge: "Nổi bật",
    theme: "sunset",
    icon: "🏎️",
    tagline: "Phanh đúng lúc, vượt mọi hỗn loạn.",
    description: "Một game đua xe tốc độ cao với điều khiển đơn giản, chướng ngại bất ngờ và những màn va chạm vui nhộn. Chơi nhanh, lập điểm cao và mở khóa các mẫu xe độc đáo.",
    features: ["Chế độ chơi nhanh 3 phút", "Bảng xếp hạng theo mùa", "Hỗ trợ tay cầm", "Thành tích và phần thưởng"],
    requirements: { os: "Windows 10 / macOS 12", cpu: "Intel i5 hoặc tương đương", ram: "8 GB", gpu: "GTX 1050 / Apple M1", storage: "3 GB" },
    release: "18/08/2026",
    size: "2.4 GB"
  },
  {
    id: "alien-outpost",
    title: "Alien Outpost",
    studio: "LacVietGames Studio",
    type: "web",
    platform: ["Trình duyệt"],
    category: ["Hành động", "Thủ thành"],
    price: 0,
    rating: 4.7,
    reviews: 932,
    badge: "Chơi miễn phí",
    theme: "alien",
    icon: "👽",
    tagline: "Khởi động phi thuyền và bảo vệ căn cứ ngoài hành tinh.",
    description: "Điều khiển người ngoài hành tinh xanh trên chiếc phi thuyền mini, chống lại từng đợt tấn công trong khi động cơ đang khởi động. Mỗi trận chỉ kéo dài vài phút nhưng đòi hỏi phản xạ nhanh.",
    features: ["Chơi ngay trên web", "Điểm số toàn cầu", "Nâng cấp vũ khí giữa trận", "Phù hợp mọi độ tuổi"],
    requirements: { os: "Chrome, Edge, Safari mới", cpu: "Bất kỳ", ram: "2 GB", gpu: "WebGL 2.0", storage: "Không cần cài đặt" },
    release: "06/08/2026",
    size: "Web game"
  },
  {
    id: "bloom-with-ai",
    title: "Bloom with AI",
    studio: "LacVietGames Studio",
    type: "web",
    platform: ["Trình duyệt", "Mobile"],
    category: ["Mô phỏng", "Giáo dục"],
    price: 0,
    rating: 4.9,
    reviews: 2104,
    badge: "Được yêu thích",
    theme: "garden",
    icon: "🌱",
    tagline: "Gieo mầm, chăm cây và khám phá khu vườn số.",
    description: "Trải nghiệm trồng cây nhẹ nhàng với các nhiệm vụ ngắn, hệ thống bộ sưu tập hoa và những gợi ý chăm sóc thông minh. Phù hợp cho booth triển lãm và lớp học.",
    features: ["Chơi ngay không cài", "Bộ sưu tập 30 loài hoa", "Nhiệm vụ theo ngày", "Giao diện thân thiện"],
    requirements: { os: "Trình duyệt hiện đại", cpu: "Bất kỳ", ram: "2 GB", gpu: "WebGL", storage: "Không cần cài đặt" },
    release: "30/07/2026",
    size: "Web game"
  },
  {
    id: "coin-empire",
    title: "Coin Empire Idle",
    studio: "Lạc Việt Forge",
    type: "download",
    platform: ["Windows", "Android"],
    category: ["Idle", "Mô phỏng"],
    price: 790,
    rating: 4.6,
    reviews: 1640,
    badge: "Mới",
    theme: "coin",
    icon: "🪙",
    tagline: "Lật xu, xây đế chế và phát triển ngay cả khi ngoại tuyến.",
    description: "Bắt đầu từ một đồng xu và xây dựng dây chuyền tự động hóa khổng lồ. Nâng cấp giá trị xu, mở khóa trang phục và quay lại nhận phần thưởng offline.",
    features: ["Tiến trình idle sâu", "Hơn 60 nâng cấp", "Phần thưởng ngoại tuyến", "Prestige nhiều tầng"],
    requirements: { os: "Windows 10 / Android 9", cpu: "Dual-core", ram: "4 GB", gpu: "Đồ họa tích hợp", storage: "1.2 GB" },
    release: "12/09/2026",
    size: "980 MB"
  },
  {
    id: "database-mystery",
    title: "Database Mystery",
    studio: "LacVietGames Education",
    type: "web",
    platform: ["Trình duyệt"],
    category: ["Puzzle", "Giáo dục"],
    price: 0,
    rating: 4.5,
    reviews: 488,
    badge: "Học mà chơi",
    theme: "database",
    icon: "🧩",
    tagline: "Giải mã dữ liệu, phá án bằng tư duy cơ sở dữ liệu.",
    description: "Một chuỗi thử thách SQL và logic được trình bày như hồ sơ điều tra. Người chơi nối dữ kiện, lọc bảng và tìm ra manh mối cuối cùng.",
    features: ["Bài chơi 5-10 phút", "Gợi ý thông minh", "Thử thách SQL trực quan", "Chứng nhận hoàn thành"],
    requirements: { os: "Trình duyệt hiện đại", cpu: "Bất kỳ", ram: "2 GB", gpu: "Không yêu cầu", storage: "Không cần cài đặt" },
    release: "21/07/2026",
    size: "Web game"
  },
  {
    id: "space-garbage",
    title: "Space Garbage",
    studio: "Lạc Việt Forge",
    type: "download",
    platform: ["Windows"],
    category: ["Phiêu lưu", "Mô phỏng"],
    price: 1490,
    oldPrice: 1990,
    rating: 4.7,
    reviews: 721,
    badge: "-25%",
    theme: "space",
    icon: "🚀",
    tagline: "Thu gom rác vũ trụ, nâng cấp trạm và sống sót giữa khoảng không.",
    description: "Rời trạm không gian, điều khiển trong môi trường không trọng lực và thu gom vật thể trôi nổi trước khi oxy cạn. Bán chiến lợi phẩm để nâng cấp thiết bị.",
    features: ["Di chuyển không trọng lực", "Vòng lặp vô tận", "Nâng cấp thiết bị", "Sự kiện thiên thạch và bão mặt trời"],
    requirements: { os: "Windows 10 64-bit", cpu: "Intel i5-8400", ram: "8 GB", gpu: "GTX 1060", storage: "6 GB" },
    release: "20/10/2026",
    size: "4.8 GB"
  },
  {
    id: "zombie-survival",
    title: "Last Stand: Infinite",
    studio: "LacVietGames Studio",
    type: "download",
    platform: ["Windows"],
    category: ["Sinh tồn", "Bắn súng"],
    price: 990,
    rating: 4.4,
    reviews: 1106,
    badge: "Co-op",
    theme: "zombie",
    icon: "🧟",
    tagline: "Sống sót càng lâu, điểm số càng cao.",
    description: "Game sinh tồn góc nhìn từ trên xuống với những đợt zombie vô hạn, kho vũ khí đa dạng và bản đồ thay đổi theo thời gian.",
    features: ["Chế độ vô tận", "Co-op 2 người", "Nhiều loại zombie", "Bảng xếp hạng tuần"],
    requirements: { os: "Windows 10", cpu: "Intel i3", ram: "6 GB", gpu: "GTX 750 Ti", storage: "2.8 GB" },
    release: "02/08/2026",
    size: "2.1 GB"
  },
  {
    id: "skyline-sprint",
    title: "Skyline Sprint",
    studio: "LacVietGames Arcade",
    type: "web",
    platform: ["Trình duyệt", "Mobile"],
    category: ["Arcade", "Casual"],
    price: 190,
    rating: 4.8,
    reviews: 3760,
    badge: "Top 1 tuần",
    theme: "sky",
    icon: "⚡",
    tagline: "Lướt qua thành phố neon và thu thập Lạc Coin.",
    description: "Một trò arcade tốc độ cao có thể chơi bằng bàn phím hoặc cảm ứng. Tránh vật cản, thu thập coin và phá kỷ lục của bạn bè.",
    features: ["Chơi ngay trên web", "Điều khiển cảm ứng", "Nhiệm vụ ngày", "Thưởng Lạc Coin thử thách"],
    requirements: { os: "Trình duyệt hiện đại", cpu: "Bất kỳ", ram: "2 GB", gpu: "Canvas 2D", storage: "Không cần cài đặt" },
    release: "01/08/2026",
    size: "Web game"
  }
];
