(() => {
  const page=document.body.dataset.page||"home";
  const qs=new URLSearchParams(location.search);
  const byId=id=>document.getElementById(id);
  const apiBase=(window.APP_CONFIG?.API_BASE_URL||"").replace(/\/$/,"");
  const fallbackGames=window.LVG_GAMES||[];
  let games=[];let me=null;

  const readStoreSession=()=>{for(const storage of [localStorage,sessionStorage]){try{const raw=storage.getItem("lacvietgamesStoreSession");if(raw)return JSON.parse(raw)}catch{}}return null};
  const readLegacySession=()=>{try{const raw=localStorage.getItem("lacvietgamesSession")||sessionStorage.getItem("lacvietgamesSession");return raw?JSON.parse(raw):null}catch{return null}};
  const session=readStoreSession()||readLegacySession();
  const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const coin=v=>Number(v||0).toLocaleString("vi-VN");

  async function api(path,auth=false){const headers={};const s=readStoreSession();if(auth&&s?.token)headers.Authorization=`Bearer ${s.token}`;const res=await fetch(`${apiBase}${path}`,{headers});const payload=await res.json().catch(()=>null);if(!res.ok||payload?.success===false)throw new Error(payload?.message||"Không thể tải dữ liệu.");return payload}

  function normalizeServerGame(g){return{dbId:g.id,id:g.slug,title:g.name,studio:g.publisherName,type:g.type,platform:g.type==="web"?["Trình duyệt"]:["Windows"],category:g.tags||[],price:Number(g.priceCoins||0),oldPrice:null,rating:4.8,reviews:0,badge:g.badge||"",theme:g.theme||"default",icon:g.icon||"🎮",tagline:g.shortDescription||"",description:g.description||"",features:[],requirements:g.requirements||{os:"Trình duyệt hiện đại",cpu:"Bất kỳ",ram:"2 GB",gpu:"WebGL",storage:"Không cần cài đặt"},release:g.releaseDate?new Date(g.releaseDate).toLocaleDateString("vi-VN"):"Sắp ra mắt",size:g.requirements?.storage||"",playUrl:g.playUrl||"",downloadUrl:g.downloadUrl||"",status:g.status||"Published"}}
  function normalizeFallback(g){return{...g,dbId:null,playUrl:g.playUrl||"",downloadUrl:g.downloadUrl||""}}

  async function loadData(){
    try{const result=await api("/api/store/games");games=(result.data||[]).map(normalizeServerGame)}catch{games=fallbackGames.map(normalizeFallback)}
    const s=readStoreSession();if(s?.token){try{me=(await api("/api/store/me",true)).data}catch{me=null}}
  }

  function isOwned(slug){return !!me?.library?.includes(slug)}
  function getGame(slug){return games.find(g=>g.id===slug)}
  function navLink(label,href,key){return`<a href="${href}" class="${page===key?"active":""}">${label}</a>`}

  function renderHeader(){const target=byId("siteHeader");if(!target)return;target.innerHTML=`<header class="site-header"><div class="topbar"><a class="logo" href="./index.html"><span class="logo-mark">LV</span><span>LacVietGames</span></a><nav class="main-nav">${navLink("Trang chủ","./index.html","home")}${navLink("Khám phá","./catalog.html","catalog")}${navLink("Web game","./catalog.html?type=web","web")}${navLink("Thư viện","./library.html","library")}</nav><form class="search-shell" id="globalSearch"><input id="globalSearchInput" type="search" placeholder="Tìm game, thể loại, studio..."><button type="submit">⌕</button></form><div class="header-actions">${session?`<a class="account-btn" href="./profile.html"><span class="avatar-mini">${esc((session.name||"L").charAt(0).toUpperCase())}</span><span>${esc(session.name||"Tài khoản")}</span></a>`:`<button class="btn btn-primary" type="button" data-open-server-auth>Đăng nhập</button>`}</div></div></header>`;byId("globalSearch")?.addEventListener("submit",e=>{e.preventDefault();const q=byId("globalSearchInput").value.trim();location.href=`./catalog.html${q?`?q=${encodeURIComponent(q)}`:""}`})}
  function renderFooter(){const target=byId("siteFooter");if(!target)return;target.innerHTML=`<footer class="site-footer"><div class="footer-inner"><div class="footer-grid"><div><a class="logo" href="./index.html"><span class="logo-mark">LV</span><span>LacVietGames</span></a><p class="footer-copy">Nền tảng game Việt với dữ liệu catalog, thư viện, ví và giao dịch được đồng bộ từ server.</p></div><div class="footer-column"><h4>Nền tảng</h4><a href="./catalog.html">Khám phá game</a><a href="./catalog.html?type=web">Web game</a><a href="./library.html">Thư viện</a><a href="./wallet.html">Lạc Coin</a></div><div class="footer-column"><h4>Nhà phát hành</h4><a href="./publisher.html">Đăng game</a><a href="./profile.html">Trang cá nhân</a><a href="./auth.html">Đăng nhập</a></div><div class="footer-column"><h4>Hỗ trợ</h4><a href="./help.html">Trung tâm trợ giúp</a><a href="./terms.html">Điều khoản sử dụng</a><a href="./privacy.html">Chính sách bảo mật</a><a href="./partners.html">Liên hệ đối tác</a></div></div><div class="footer-bottom"><span>© 2026 LacVietGames.</span><span>Made for Vietnamese gamers</span></div></div></footer>`}

  function gameCard(g){return`<article class="game-card"><a href="./game.html?id=${encodeURIComponent(g.id)}"><div class="game-cover theme-${esc(g.theme)}"><span>${esc(g.icon)}</span>${g.badge?`<span class="game-badge">${esc(g.badge)}</span>`:""}</div></a><div class="game-info"><div class="game-meta"><span>${g.type==="web"?"WEB GAME":"TẢI VỀ"}</span><span>${esc(g.platform[0]||"")}</span></div><a href="./game.html?id=${encodeURIComponent(g.id)}"><h3>${esc(g.title)}</h3><p>${esc(g.category.join(" · "))}</p></a><div class="game-foot"><span class="rating">★ ${g.rating}</span>${g.price===0?`<span class="price free">Miễn phí</span>`:`<span class="price">${coin(g.price)} LC</span>`}</div></div></article>`}

  function renderHome(){byId("app").innerHTML=`<section class="hero"><div class="hero-copy"><span class="eyebrow">Nền tảng game Việt thế hệ mới</span><h1>Chơi ngay.<br><span>Tải về. Kết nối.</span></h1><p>Khám phá game được quản lý trực tiếp từ catalog LacVietGames.</p><div class="hero-actions"><a class="btn btn-primary" href="./catalog.html">Khám phá kho game</a><a class="btn btn-secondary" href="./publisher.html">Đăng game của bạn</a></div><div class="hero-stats"><div><strong>${games.length}</strong><small>Game đã xuất bản</small></div><div><strong>Server</strong><small>Dữ liệu đồng bộ</small></div><div><strong>24/7</strong><small>Web platform</small></div></div></div><div class="hero-art">🎮</div></section><section class="section"><div class="section-head"><div><span class="eyebrow">Catalog</span><h2>Game mới trên LacVietGames</h2><p>Chỉ game đã được Admin duyệt mới xuất hiện tại đây.</p></div><a class="section-link" href="./catalog.html">Xem tất cả →</a></div><div class="game-grid">${games.slice(0,8).map(gameCard).join("")||`<div class="empty-state">Chưa có game được xuất bản.</div>`}</div></section><section class="section promo-row"><article class="promo"><span class="eyebrow">Lạc Coin</span><h3>Một ví trên server</h3><p>Số dư chỉ tồn tại sau đăng nhập và mọi thay đổi đều có transaction.</p><a class="btn btn-primary" href="./wallet.html">Mở ví</a><div class="promo-icon">🪙</div></article><article class="promo green"><span class="eyebrow">Publisher</span><h3>Đưa game của bạn lên store</h3><p>Gửi game, theo dõi Pending và nhận thông báo khi Admin duyệt.</p><a class="btn btn-secondary" href="./publisher.html">Publisher Center</a><div class="promo-icon">🚀</div></article></section>`}

  function renderCatalog(){const q0=(qs.get("q")||"").toLowerCase(),type0=qs.get("type")||"all";byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Game store</span><h2>Khám phá kho game</h2><p>Dữ liệu lấy trực tiếp từ bảng games + tags.</p></div></div><div class="catalog-toolbar"><input id="catalogSearch" class="field-control" type="search" value="${esc(qs.get("q")||"")}" placeholder="Tìm game..."><select id="catalogType"><option value="all">Tất cả</option><option value="web">Web game</option><option value="download">Tải về</option></select><span id="resultCount" class="result-count"></span></div><div id="catalogGrid" class="game-grid"></div>`;byId("catalogType").value=type0;const update=()=>{const q=byId("catalogSearch").value.trim().toLowerCase();const type=byId("catalogType").value;const filtered=games.filter(g=>(!q||`${g.title} ${g.studio} ${g.category.join(" ")}`.toLowerCase().includes(q))&&(type==="all"||g.type===type));byId("resultCount").textContent=`${filtered.length} game`;byId("catalogGrid").innerHTML=filtered.map(gameCard).join("")||`<div class="empty-state" style="grid-column:1/-1"><h3>Không tìm thấy game</h3></div>`};byId("catalogSearch").addEventListener("input",update);byId("catalogType").addEventListener("change",update);if(q0)byId("catalogSearch").value=q0;update()}

  function renderGameDetail(){const g=getGame(qs.get("id"))||games[0];if(!g){byId("app").innerHTML='<div class="empty-state"><h2>Không tìm thấy game</h2></div>';return}const owned=isOwned(g.id);const action=owned?(g.type==="web"?`<a class="btn btn-primary" href="./play.html?id=${encodeURIComponent(g.id)}">▶ Chơi ngay</a>`:`<a class="btn btn-primary" href="./library.html?install=${encodeURIComponent(g.id)}">↓ Tải xuống</a>`):`<button id="buyGame" class="btn btn-primary">${g.price===0?"Thêm miễn phí vào thư viện":`Mua ${coin(g.price)} LC`}</button>`;byId("app").innerHTML=`<section class="detail-hero"><div class="detail-visual theme-${esc(g.theme)}">${esc(g.icon)}</div><div class="detail-copy"><span class="eyebrow">${g.type==="web"?"Web game":"Game tải về"}</span><h1>${esc(g.title)}</h1><p class="detail-tagline">${esc(g.tagline)}</p><div class="tag-row">${g.category.map(c=>`<span class="tag">${esc(c)}</span>`).join("")}</div><div class="detail-price">${g.price===0?"Miễn phí":`${coin(g.price)} Lạc Coin`}</div><div class="detail-actions">${action}</div></div></section><section class="detail-grid"><div class="profile-section"><article class="content-card"><h2>Giới thiệu</h2><p>${esc(g.description)}</p></article></div><aside class="profile-section"><article class="content-card"><h3>Thông tin game</h3><div class="requirement-list"><div><span>Nhà phát hành</span><b>${esc(g.studio)}</b></div><div><span>Ngày phát hành</span><b>${esc(g.release)}</b></div><div><span>Loại</span><b>${g.type==="web"?"Web game":"Tải về"}</b></div></div></article><article class="content-card"><h3>Cấu hình đề nghị</h3><div class="requirement-list"><div><span>Hệ điều hành</span><b>${esc(g.requirements.os)}</b></div><div><span>CPU</span><b>${esc(g.requirements.cpu)}</b></div><div><span>RAM</span><b>${esc(g.requirements.ram)}</b></div><div><span>GPU</span><b>${esc(g.requirements.gpu)}</b></div><div><span>Dung lượng</span><b>${esc(g.requirements.storage)}</b></div></div></article></aside></section>`}

  async function renderLibrary(){const s=readStoreSession();if(!s?.token){byId("app").innerHTML=`<div class="empty-state"><h2>Đăng nhập để xem thư viện</h2><p>Thư viện được lưu trên server theo tài khoản.</p><button class="btn btn-primary" data-open-server-auth>Đăng nhập / Đăng ký</button></div>`;return}try{const result=await api("/api/store/library",true);const list=(result.data||[]).map(x=>normalizeServerGame(x.game));const install=qs.get("install");const target=list.find(g=>g.id===install&&g.type==="download");byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Thư viện server</span><h2>Game của tôi</h2></div></div>${target?`<article class="content-card" style="margin-bottom:22px"><h3>Sẵn sàng tải ${esc(target.title)}</h3>${target.downloadUrl?`<a class="btn btn-primary" href="${esc(target.downloadUrl)}" target="_blank" rel="noopener">Tải file từ nhà phát hành</a>`:`<p>Nhà phát hành chưa cấu hình Download URL.</p>`}</article>`:""}<div class="game-grid">${list.map(gameCard).join("")||'<div class="empty-state">Thư viện đang trống.</div>'}</div>`}catch(e){byId("app").innerHTML=`<div class="empty-state"><h2>Không tải được thư viện</h2><p>${esc(e.message)}</p></div>`}}

  function renderWallet(){const s=readStoreSession();if(!s?.token){byId("app").innerHTML=`<div class="empty-state"><h2>Đăng nhập để mở ví Lạc Coin</h2><p>Bạn chưa có coin khi chưa đăng nhập.</p><button class="btn btn-primary" data-open-server-auth>Đăng nhập / Đăng ký</button></div>`;return}const packs=[[500,"49.000đ"],[1200,"99.000đ"],[2600,"199.000đ"],[7000,"499.000đ"]];byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">LacViet Wallet</span><h2>Ví Lạc Coin</h2><p>Số dư và lịch sử giao dịch lấy từ server.</p></div></div><section class="wallet-hero"><div class="wallet-balance"><small>Số dư khả dụng</small><strong>Đang tải...</strong><p style="color:#d3daf0">Quà người mới chỉ được cộng sau lần đăng nhập thành công đầu tiên.</p></div><div class="wallet-mark">🪙</div></section><section class="section"><div class="section-head"><div><h2>Nạp Lạc Coin</h2><p>Thanh toán qua payOS; coin chỉ cộng khi webhook hợp lệ tới server.</p></div></div><div class="coin-pack-grid">${packs.map(([c,p])=>`<button class="coin-pack" data-pack="${c}"><div class="coin-icon">🪙</div><strong>${coin(c)} LC</strong><small>${p}</small></button>`).join("")}</div></section><section class="section content-card"><div class="section-head"><div><h2>Lịch sử giao dịch</h2></div></div><div class="transaction-list"><div class="portal-empty">Đang tải từ server...</div></div></section>`}

  function renderProfile(){if(!session){byId("app").innerHTML=`<div class="empty-state"><h2>Bạn chưa đăng nhập</h2><button class="btn btn-primary" data-open-server-auth>Đăng nhập</button></div>`;return}byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Player profile</span><h2>Trang cá nhân</h2></div><a class="btn btn-secondary" href="./edit-profile.html">Chỉnh sửa hồ sơ</a></div><div class="profile-layout"><aside class="profile-card"><div class="profile-avatar">${esc((session.name||"LV").charAt(0).toUpperCase())}</div><h2>${esc(session.name||"")}</h2><p>${esc(session.email||"")}</p><span class="tag">${esc(session.role||"User")}</span></aside><section class="profile-section"><article class="content-card"><h2>Tài khoản LacVietGames</h2><p>Email đã xác minh và dữ liệu ví/thư viện được quản lý trên server.</p><div class="admin-actions"><a class="btn btn-secondary" href="./publisher.html">Publisher Center</a>${String(session.role).toLowerCase()==="admin"?'<a class="btn btn-primary" href="./admin.html">Admin Center</a>':""}<button id="logoutProfile" class="btn btn-secondary" type="button">Đăng xuất</button></div></article></section></div>`;byId("logoutProfile").addEventListener("click",()=>{for(const st of[localStorage,sessionStorage]){st.removeItem("lacvietgamesStoreSession");st.removeItem("lacvietgamesSession")}location.href="./index.html"})}

  function renderEditProfile(){if(!session){location.href="./auth.html";return}byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Account settings</span><h2>Chỉnh sửa hồ sơ</h2></div><a class="btn btn-secondary" href="./profile.html">← Quay lại</a></div><article class="content-card"><p>Thông tin tên/quyền tài khoản lõi đang được quản lý ở server. Trang chỉnh hồ sơ mở rộng sẽ nối API profile riêng sau.</p><p>Email: <b>${esc(session.email||"")}</b></p></article>`}

  async function renderPlay(){const s=readStoreSession();if(!s?.token){byId("app").innerHTML=`<div class="empty-state"><h2>Đăng nhập để chơi</h2><p>Bạn phải đăng nhập trước khi mở Web Game.</p><button class="btn btn-primary" data-open-server-auth>Đăng nhập / Đăng ký</button></div>`;return}const g=getGame(qs.get("id"));if(!g){byId("app").innerHTML='<div class="empty-state">Không tìm thấy game.</div>';return}if(!isOwned(g.id)){location.href=`./game.html?id=${encodeURIComponent(g.id)}`;return}if(g.type!=="web"){location.href=`./game.html?id=${encodeURIComponent(g.id)}`;return}byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Đang chơi</span><h2>${esc(g.title)}</h2><p>${esc(g.tagline)}</p></div><a class="btn btn-secondary" href="./game.html?id=${encodeURIComponent(g.id)}">Thông tin game</a></div>${g.playUrl?`<div class="play-shell" style="display:block"><iframe title="${esc(g.title)}" src="${esc(g.playUrl)}" style="width:100%;height:75vh;border:0;border-radius:18px;background:#000" allowfullscreen></iframe></div>`:`<div class="empty-state"><h3>Game chưa có Play URL</h3><p>Nhà phát hành cần cập nhật URL chạy Web Game.</p></div>`}`}

  async function init(){await loadData();renderHeader();renderFooter();const renderer={home:renderHome,catalog:renderCatalog,game:renderGameDetail,library:renderLibrary,wallet:renderWallet,profile:renderProfile,editProfile:renderEditProfile,play:renderPlay}[page]||renderHome;await renderer()}
  init();
})();