(() => {
  const page=document.body.dataset.page||"home";
  const qs=new URLSearchParams(location.search);
  const byId=id=>document.getElementById(id);
  const apiBase=(window.APP_CONFIG?.API_BASE_URL||"").replace(/\/$/,"");
  let games=[];let me=null;let catalogUnavailable=false;

  const readStoreSession=()=>{for(const storage of [localStorage,sessionStorage]){try{const raw=storage.getItem("lacvietgamesStoreSession");if(raw)return JSON.parse(raw)}catch{}}return null};
  const readLegacySession=()=>{try{const raw=localStorage.getItem("lacvietgamesSession")||sessionStorage.getItem("lacvietgamesSession");return raw?JSON.parse(raw):null}catch{return null}};
  const session=readStoreSession()||readLegacySession();
  const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const coin=v=>Number(v||0).toLocaleString("vi-VN");

  async function api(path,auth=false){const headers={};const s=readStoreSession();if(auth&&s?.token)headers.Authorization=`Bearer ${s.token}`;const res=await fetch(`${apiBase}${path}`,{headers});const payload=await res.json().catch(()=>null);if(!res.ok||payload?.success===false)throw new Error(payload?.message||"Không thể tải dữ liệu.");return payload}

  function normalizeServerGame(g){return{dbId:g.id,id:g.slug,title:g.name,studio:g.publisherName,type:g.type,platform:g.type==="web"?["Trình duyệt"]:["Windows"],category:g.tags||[],price:Number(g.priceCoins||0),oldPrice:null,rating:null,reviews:null,badge:g.badge||"",theme:g.theme||"default",icon:g.icon||"🎮",tagline:g.shortDescription||"",description:g.description||"",features:[],requirements:g.requirements||{os:"Trình duyệt hiện đại",cpu:"Bất kỳ",ram:"2 GB",gpu:"WebGL",storage:"Không cần cài đặt"},release:g.releaseDate?new Date(g.releaseDate).toLocaleDateString("vi-VN"):"Sắp ra mắt",size:g.requirements?.storage||"",playUrl:g.playUrl||"",downloadUrl:g.downloadUrl||"",status:g.status||"Published"}}

  async function loadData(){
    try{const result=await api("/api/store/games");games=(result.data||[]).map(normalizeServerGame);catalogUnavailable=false}catch{games=[];catalogUnavailable=true}
    const s=readStoreSession();if(s?.token){try{me=(await api("/api/store/me",true)).data}catch{me=null}}
  }

  function isOwned(slug){return !!me?.library?.includes(slug)}
  function getGame(slug){return games.find(g=>g.id===slug)}
  function navLink(label,href,key){return`<a href="${href}" class="${page===key?"active":""}">${label}</a>`}

  function renderHeader(){const target=byId("siteHeader");if(!target)return;target.innerHTML=`<header class="site-header"><div class="topbar"><a class="logo" href="./index.html"><span class="logo-mark">LV</span><span>LacVietGames</span></a><nav class="main-nav">${navLink("Trang chủ","./index.html","home")}${navLink("Khám phá","./catalog.html","catalog")}${navLink("Chơi trực tuyến","./catalog.html?type=web","web")}${navLink("Thư viện","./library.html","library")}</nav><form class="search-shell" id="globalSearch"><input id="globalSearchInput" type="search" placeholder="Tìm game, thể loại, nhà phát hành..."><button type="submit" aria-label="Tìm kiếm">⌕</button></form><div class="header-actions">${session?`<a class="account-btn" href="./profile.html"><span class="avatar-mini">${esc((session.name||"L").charAt(0).toUpperCase())}</span><span>${esc(session.name||"Tài khoản")}</span></a>`:`<button class="btn btn-primary" type="button" data-open-server-auth>Đăng nhập</button>`}</div></div></header>`;byId("globalSearch")?.addEventListener("submit",e=>{e.preventDefault();const q=byId("globalSearchInput").value.trim();location.href=`./catalog.html${q?`?q=${encodeURIComponent(q)}`:""}`})}
  function renderFooter(){const target=byId("siteFooter");if(!target)return;target.innerHTML=`<footer class="site-footer"><div class="footer-inner"><div class="footer-grid"><div><a class="logo" href="./index.html"><span class="logo-mark">LV</span><span>LacVietGames</span></a><p class="footer-copy">Khám phá, sở hữu và trải nghiệm những trò chơi được tuyển chọn trên một nền tảng dành cho cộng đồng game Việt.</p></div><div class="footer-column"><h4>Khám phá</h4><a href="./catalog.html">Kho trò chơi</a><a href="./catalog.html?type=web">Chơi trực tuyến</a><a href="./library.html">Thư viện</a><a href="./wallet.html">Lạc Coin</a></div><div class="footer-column"><h4>Nhà phát hành</h4><a href="./publisher.html">Trung tâm phát hành</a><a href="./profile.html">Trang cá nhân</a><a href="./auth.html">Đăng nhập</a></div><div class="footer-column"><h4>Hỗ trợ</h4><a href="./help.html">Trung tâm trợ giúp</a><a href="./terms.html">Điều khoản sử dụng</a><a href="./privacy.html">Chính sách bảo mật</a><a href="./partners.html">Liên hệ đối tác</a></div></div><div class="footer-bottom"><span>© 2026 LacVietGames.</span><span>Dành cho cộng đồng game Việt</span></div></div></footer>`}

  function gameCard(g){return`<article class="game-card"><a href="./game.html?id=${encodeURIComponent(g.id)}"><div class="game-cover theme-${esc(g.theme)}"><span>${esc(g.icon)}</span>${g.badge?`<span class="game-badge">${esc(g.badge)}</span>`:""}</div></a><div class="game-info"><div class="game-meta"><span>${g.type==="web"?"CHƠI TRỰC TUYẾN":"TẢI VỀ"}</span><span>${esc(g.platform[0]||"")}</span></div><a href="./game.html?id=${encodeURIComponent(g.id)}"><h3>${esc(g.title)}</h3><p>${esc(g.category.join(" · "))}</p></a><div class="game-foot">${g.rating!=null?`<span class="rating">★ ${Number(g.rating).toFixed(1)}</span>`:'<span></span>'}${g.price===0?`<span class="price free">Miễn phí</span>`:`<span class="price">${coin(g.price)} LC</span>`}</div></div></article>`}

  function renderHome(){const webCount=games.filter(g=>g.type==="web").length,downloadCount=games.filter(g=>g.type==="download").length;byId("app").innerHTML=`<section class="hero"><div class="hero-copy"><span class="eyebrow">Trải nghiệm game theo cách của bạn</span><h1>Khám phá thế giới game.<br><span>Chơi theo phong cách riêng.</span></h1><p>Từ những trò chơi có thể mở ngay trên trình duyệt đến các phiên bản tải về, LacVietGames mang mọi trải nghiệm vào một không gian thống nhất, dễ tiếp cận và đáng tin cậy.</p><div class="hero-actions"><a class="btn btn-primary" href="./catalog.html">Khám phá ngay</a><a class="btn btn-secondary" href="./publisher.html">Phát hành game</a></div><div class="hero-stats"><div><strong>${games.length}</strong><small>Trò chơi hiện có</small></div><div><strong>${webCount}</strong><small>Chơi trực tuyến</small></div><div><strong>${downloadCount}</strong><small>Phiên bản tải về</small></div></div></div><div class="hero-art">🎮</div></section><section class="section"><div class="section-head"><div><span class="eyebrow">Mới trên LacVietGames</span><h2>Trò chơi đáng chú ý</h2><p>Những tựa game mới nhất đã sẵn sàng để khám phá.</p></div><a class="section-link" href="./catalog.html">Xem tất cả →</a></div><div class="game-grid">${games.slice(0,8).map(gameCard).join("")||(catalogUnavailable?`<div class="empty-state">Kho trò chơi tạm thời chưa thể tải. Vui lòng thử lại sau.</div>`:`<div class="empty-state">Các trò chơi mới đang được cập nhật.</div>`)}</div></section><section class="section promo-row"><article class="promo"><span class="eyebrow">Lạc Coin</span><h3>Một số dư, nhiều trải nghiệm</h3><p>Quản lý số dư, nạp Lạc Coin và theo dõi các giao dịch ngay trong tài khoản LacVietGames.</p><a class="btn btn-primary" href="./wallet.html">Mở ví Lạc Coin</a><div class="promo-icon">🪙</div></article><article class="promo green"><span class="eyebrow">Dành cho nhà phát hành</span><h3>Đưa trò chơi đến nhiều người chơi hơn</h3><p>Gửi trò chơi, quản lý phiên bản và theo dõi trạng thái phát hành trong một không gian thống nhất.</p><a class="btn btn-secondary" href="./publisher.html">Trung tâm phát hành</a><div class="promo-icon">🚀</div></article></section>`}

  function renderCatalog(){const q0=(qs.get("q")||"").toLowerCase(),type0=qs.get("type")||"all";byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Kho trò chơi</span><h2>Tìm trải nghiệm phù hợp</h2><p>Duyệt theo tên, thể loại hoặc cách chơi.</p></div></div><div class="catalog-toolbar"><input id="catalogSearch" class="field-control" type="search" value="${esc(qs.get("q")||"")}" placeholder="Tìm game..."><select id="catalogType"><option value="all">Tất cả</option><option value="web">Chơi trực tuyến</option><option value="download">Tải về</option></select><span id="resultCount" class="result-count"></span></div><div id="catalogGrid" class="game-grid"></div>`;byId("catalogType").value=type0;const update=()=>{const q=byId("catalogSearch").value.trim().toLowerCase();const type=byId("catalogType").value;const filtered=games.filter(g=>(!q||`${g.title} ${g.studio} ${g.category.join(" ")}`.toLowerCase().includes(q))&&(type==="all"||g.type===type));byId("resultCount").textContent=`${filtered.length} trò chơi`;byId("catalogGrid").innerHTML=filtered.map(gameCard).join("")||(catalogUnavailable?`<div class="empty-state" style="grid-column:1/-1"><h3>Chưa thể tải kho trò chơi</h3><p>Vui lòng thử lại sau.</p></div>`:`<div class="empty-state" style="grid-column:1/-1"><h3>Không tìm thấy trò chơi phù hợp</h3></div>`)};byId("catalogSearch").addEventListener("input",update);byId("catalogType").addEventListener("change",update);if(q0)byId("catalogSearch").value=q0;update()}

  function renderGameDetail(){const g=getGame(qs.get("id"));if(!g){byId("app").innerHTML='<div class="empty-state"><h2>Không tìm thấy trò chơi</h2><p>Trò chơi có thể đã được ẩn hoặc đường dẫn không còn hợp lệ.</p></div>';return}const owned=isOwned(g.id);const action=owned?(g.type==="web"?`<a class="btn btn-primary" href="./play.html?id=${encodeURIComponent(g.id)}">▶ Chơi ngay</a>`:`<a class="btn btn-primary" href="./library.html?install=${encodeURIComponent(g.id)}">↓ Tải xuống</a>`):`<button id="buyGame" class="btn btn-primary">${g.price===0?"Thêm vào thư viện":`Mua với ${coin(g.price)} LC`}</button>`;byId("app").innerHTML=`<section class="detail-hero"><div class="detail-visual theme-${esc(g.theme)}">${esc(g.icon)}</div><div class="detail-copy"><span class="eyebrow">${g.type==="web"?"Chơi trực tuyến":"Phiên bản tải về"}</span><h1>${esc(g.title)}</h1><p class="detail-tagline">${esc(g.tagline)}</p><div class="tag-row">${g.category.map(c=>`<span class="tag">${esc(c)}</span>`).join("")}</div><div class="detail-price">${g.price===0?"Miễn phí":`${coin(g.price)} Lạc Coin`}</div><div class="detail-actions">${action}</div></div></section><section class="detail-grid"><div class="profile-section"><article class="content-card"><h2>Giới thiệu</h2><p>${esc(g.description)}</p></article></div><aside class="profile-section"><article class="content-card"><h3>Thông tin trò chơi</h3><div class="requirement-list"><div><span>Nhà phát hành</span><b>${esc(g.studio)}</b></div><div><span>Ngày phát hành</span><b>${esc(g.release)}</b></div><div><span>Hình thức</span><b>${g.type==="web"?"Chơi trực tuyến":"Tải về"}</b></div></div></article><article class="content-card"><h3>Cấu hình đề nghị</h3><div class="requirement-list"><div><span>Hệ điều hành</span><b>${esc(g.requirements.os)}</b></div><div><span>CPU</span><b>${esc(g.requirements.cpu)}</b></div><div><span>RAM</span><b>${esc(g.requirements.ram)}</b></div><div><span>GPU</span><b>${esc(g.requirements.gpu)}</b></div><div><span>Dung lượng</span><b>${esc(g.requirements.storage)}</b></div></div></article></aside></section>`}

  async function renderLibrary(){const s=readStoreSession();if(!s?.token){byId("app").innerHTML=`<div class="empty-state"><h2>Thư viện của bạn đang chờ</h2><p>Đăng nhập để xem những trò chơi đã sở hữu.</p><button class="btn btn-primary" data-open-server-auth>Đăng nhập / Đăng ký</button></div>`;return}try{const result=await api("/api/store/library",true);const list=(result.data||[]).map(x=>normalizeServerGame(x.game));const install=qs.get("install");const target=list.find(g=>g.id===install&&g.type==="download");byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Thư viện của bạn</span><h2>Trò chơi đã sở hữu</h2></div></div>${target?`<article class="content-card" style="margin-bottom:22px"><h3>${esc(target.title)}</h3>${target.downloadUrl?`<a class="btn btn-primary" href="${esc(target.downloadUrl)}" target="_blank" rel="noopener">Tải xuống</a>`:`<p>Phiên bản tải xuống hiện chưa khả dụng.</p>`}</article>`:""}<div class="game-grid">${list.map(gameCard).join("")||'<div class="empty-state">Thư viện hiện chưa có trò chơi.</div>'}</div>`}catch(e){byId("app").innerHTML=`<div class="empty-state"><h2>Chưa thể mở thư viện</h2><p>${esc(e.message)}</p></div>`}}

  function renderWallet(){const s=readStoreSession();if(!s?.token){byId("app").innerHTML=`<div class="empty-state"><h2>Đăng nhập để sử dụng Lạc Coin</h2><p>Số dư và giao dịch được gắn với tài khoản LacVietGames.</p><button class="btn btn-primary" data-open-server-auth>Đăng nhập / Đăng ký</button></div>`;return}byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Lạc Coin</span><h2>Ví của bạn</h2><p>Quản lý số dư và các giao dịch gần đây.</p></div></div><section class="wallet-hero"><div class="wallet-balance"><small>Số dư khả dụng</small><strong>Đang tải...</strong></div><div class="wallet-mark">🪙</div></section><section class="section"><div class="section-head"><div><h2>Nạp Lạc Coin</h2><p>Chọn gói phù hợp để tiếp tục.</p></div></div><div class="coin-pack-grid"><div class="portal-empty">Đang tải các gói Lạc Coin...</div></div></section><section class="section content-card"><div class="section-head"><div><h2>Lịch sử giao dịch</h2></div></div><div class="transaction-list"><div class="portal-empty">Đang tải...</div></div></section>`}

  function renderProfile(){if(!session){byId("app").innerHTML=`<div class="empty-state"><h2>Đăng nhập để xem trang cá nhân</h2><button class="btn btn-primary" data-open-server-auth>Đăng nhập</button></div>`;return}byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Tài khoản</span><h2>Trang cá nhân</h2></div><a class="btn btn-secondary" href="./edit-profile.html">Chỉnh sửa hồ sơ</a></div><div class="profile-layout"><aside class="profile-card"><div class="profile-avatar">${esc((session.name||"LV").charAt(0).toUpperCase())}</div><h2>${esc(session.name||"")}</h2><p>${esc(session.email||"")}</p></aside><section class="profile-section"><article class="content-card"><h2>LacVietGames</h2><p>Quản lý hồ sơ, bảo mật tài khoản và các khu vực dành riêng cho bạn.</p><div class="admin-actions"><a class="btn btn-secondary" href="./publisher.html">Trung tâm phát hành</a>${String(session.role).toLowerCase()==="admin"?'<a class="btn btn-primary" href="./admin.html">Quản trị hệ thống</a>':""}<button id="logoutProfile" class="btn btn-secondary" type="button">Đăng xuất</button></div></article></section></div>`;byId("logoutProfile").addEventListener("click",()=>{for(const st of[localStorage,sessionStorage]){st.removeItem("lacvietgamesStoreSession");st.removeItem("lacvietgamesSession")}location.href="./index.html"})}

  function renderEditProfile(){if(!session){location.href="./auth.html";return}byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Tài khoản</span><h2>Chỉnh sửa hồ sơ</h2></div><a class="btn btn-secondary" href="./profile.html">← Quay lại</a></div><article class="content-card"><h3>Thông tin tài khoản</h3><p>Một số thay đổi liên quan đến bảo mật có thể yêu cầu xác minh lại danh tính.</p><p>Email: <b>${esc(session.email||"")}</b></p></article>`}

  async function renderPlay(){const s=readStoreSession();if(!s?.token){byId("app").innerHTML=`<div class="empty-state"><h2>Đăng nhập để bắt đầu chơi</h2><p>Tiếp tục bằng tài khoản LacVietGames của bạn.</p><button class="btn btn-primary" data-open-server-auth>Đăng nhập / Đăng ký</button></div>`;return}const g=getGame(qs.get("id"));if(!g){byId("app").innerHTML='<div class="empty-state">Không tìm thấy trò chơi.</div>';return}if(!isOwned(g.id)){location.href=`./game.html?id=${encodeURIComponent(g.id)}`;return}if(g.type!=="web"){location.href=`./game.html?id=${encodeURIComponent(g.id)}`;return}byId("app").innerHTML=`<div class="section-head"><div><span class="eyebrow">Đang chơi</span><h2>${esc(g.title)}</h2><p>${esc(g.tagline)}</p></div><a class="btn btn-secondary" href="./game.html?id=${encodeURIComponent(g.id)}">Thông tin trò chơi</a></div>${g.playUrl?`<div class="play-shell" style="display:block"><iframe title="${esc(g.title)}" src="${esc(g.playUrl)}" style="width:100%;height:75vh;border:0;border-radius:18px;background:#000" allowfullscreen></iframe></div>`:`<div class="empty-state"><h3>Chưa thể bắt đầu trò chơi</h3><p>Phiên bản chơi trực tuyến hiện chưa khả dụng. Vui lòng quay lại sau.</p></div>`}`}

  async function init(){await loadData();renderHeader();renderFooter();const renderer={home:renderHome,catalog:renderCatalog,game:renderGameDetail,library:renderLibrary,wallet:renderWallet,profile:renderProfile,editProfile:renderEditProfile,play:renderPlay}[page]||renderHome;await renderer()}
  init();
})();
