(() => {
  const apiBase=(window.APP_CONFIG?.API_BASE_URL||"").replace(/\/$/,"");
  const COOKIE_SENTINEL=window.LVGSession?.cookieSentinel||"cookie.session";
  const root=document.getElementById("wishlistGrid");
  const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const fmt=n=>Number(n||0).toLocaleString("vi-VN");
  const read=()=>window.LVGSession?.read?.()||null;
  async function api(path,opt={}){const s=read();if(opt.auth&&!s?.token)throw Object.assign(new Error("Bạn cần đăng nhập."),{status:401});const h={"Content-Type":"application/json","Accept":"application/json"};if(opt.auth&&s.token!==COOKIE_SENTINEL)h.Authorization=`Bearer ${s.token}`;const r=await fetch(`${apiBase}${path}`,{method:opt.method||"GET",credentials:"include",cache:"no-store",headers:h});const p=await r.json().catch(()=>null);if(!r.ok||p?.success===false)throw Object.assign(new Error(p?.message||"Không tải được dữ liệu."),{status:r.status});return p}
  async function load(){if(!read()?.token){root.innerHTML='<div class="empty-state"><h2>Đăng nhập để xem trò chơi yêu thích</h2><button class="btn btn-primary" data-open-server-auth>Đăng nhập / Đăng ký</button></div>';return}root.innerHTML='<div class="empty-state">Đang tải...</div>';try{const [w,g]=await Promise.all([api("/api/store/wishlist",{auth:true}),api("/api/store/games")]);const ids=new Set(w.data||[]),list=(g.data||[]).filter(x=>ids.has(x.id));root.innerHTML=list.length?list.map(x=>`<article class="wishlist-item"><a href="./game.html?id=${encodeURIComponent(x.slug)}"><div class="wishlist-cover" ${x.coverUrl?`style="background-image:url('${esc(x.coverUrl)}')"`:""}>${x.coverUrl?"":esc(x.icon||"🎮")}</div></a><div class="wishlist-body"><h3>${esc(x.name)}</h3><p>${esc(x.publisherName)}</p><div class="wishlist-price">${x.discountPercent?`<span class="old-price">${fmt(x.originalPriceCoins)} LC</span> `:""}${fmt(x.effectivePriceCoins??x.priceCoins)} LC ${x.discountPercent?`<span class="sale-badge">-${x.discountPercent}%</span>`:""}</div><div class="wishlist-actions"><a class="btn btn-primary" href="./game.html?id=${encodeURIComponent(x.slug)}">Xem trò chơi</a><button class="btn btn-secondary" data-remove-wish="${x.id}">Bỏ yêu thích</button></div></div></article>`).join(""):'<div class="empty-state"><h2>Chưa có trò chơi yêu thích</h2><p>Lưu những trò chơi đáng chú ý để quay lại sau.</p><a class="btn btn-primary" href="./catalog.html">Khám phá trò chơi</a></div>'}catch(e){root.innerHTML=`<div class="empty-state"><h2>Chưa thể tải danh sách</h2><p>${esc(e.message)}</p></div>`}}
  document.addEventListener("click",async e=>{const b=e.target.closest("[data-remove-wish]");if(!b)return;b.disabled=true;try{await api(`/api/store/wishlist/${b.dataset.removeWish}/toggle`,{method:"POST",auth:true});load()}catch(x){alert(x.message);b.disabled=false}});window.addEventListener("lvg:session-hydrated",load);window.addEventListener("lvg:session-invalid",load);setTimeout(load,350);
})();
